version: '3.9'

services:
  flask:
    build: .
    container_name: flaskApp
    volumes:
      - .:/flaskApp
    restart: always
    ports:
      - "5000:5000"
    command: >
      sh -c "python3 app.py"
