version: '3.9'


networks:
  5G-WIFI:
    driver: bridge

services:
  flask:
    build: ./flask
    container_name: flask
    volumes:
      - ./flask:/flaskApp
    restart: always
    ports:
      - "5000:5000"
    command: >
      sh -c "uwsgi --ini app.ini --http :5000"
    networks:
      - 5G-WIFI

  nginx_webserver:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - flask
    networks:
      - 5G-WIFI
    command: >
      sh -c "nginx -g 'daemon off;'"
    
    



